### ISSUE TITLE
Feature Request: Need two separate columns on both sides of the desktop screen

### ISSUE THREAD

**Issue by sbhhdp** [slgobinath/gcalendar#16]
Hi,

Really love the effort you have put into this desklet. This should be a relatively simple feature request. I would like to display two different calendars on two different locations. This would display the information in an organized manner and decrease the clutter. Thanks.

**Comment by slgobinath** [comment]
Hi, If I understand correctly you wanna show two desklets for two different Google accounts at the same time?
It is already supported using the accounts feature. You need to run `gcalendar --account foo` (instead of `foo` use any alphanumerical name) to authorize to a new account.
Then add a new desklet and set the gcalendar Account Id as `foo` (or the id you used).

If you mean something else, please let me know.
